### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by LuigiSigillo** [2165998/TarGAN#3]
Hi, I see in your paper you showed how well this network performs with different metrics (FID, S-score etc.)
Is there the possibility you will also upload the part of the code where you have done the evaluation in this repository?
Thank you

**Comment by cs-xiao** [comment]
Hi, I am sorry, this part of the code needs some time to sort out.
We refer to the part of implementation of FID from [StarGAN2](https://github.com/clovaai/stargan-v2/blob/master/metrics/fid.py).
And S-score is just the **DICE metrics** to evaluate the 3D segmentation performance.
Thank you~

**Comment by LuigiSigillo** [comment]
Hi, I understand that this will take time for you to sort out.
May I know how you handled the fact that the inception network used to calculate the FID has 3 channels (RGB) in input while those medical images have just one channel ?
Thanks

**Comment by cs-xiao** [comment]
Hi, there is a common way to handled you issue - copy one channel into three channels  (RGB).
But in our work, we use the Models Genesis to calculate the FID (You can see the details in our supplementary material). 
Thank you~

**Comment by LuigiSigillo** [comment]
Hi, I've used the "classical" method to handle this problem, copying the channel into three, but now I will check this model genesis solution (I didn't know about the supplementary material). Anyway I will appreciate to see your final implementation of this evaluation part, whenever you are ready to publish it.
Thank you.

**Comment by LuigiSigillo** [comment]
Hi there,
I tried to use the model genesis approach, but I have some doubt about the correct implementation.
After the global avarege pooling in the last encoder layer, the tensor in output has a shape of (#batch_size, 512).
What's the continue to have the correct FID results ? 
Do you perform some mean and that's the FID?
Am I missing something?
